schlagmichdoch/PairDrop

docs/host-your-own.md
=> docs(ghcr) add deployment notes for ghcr

.github/workflows/github-image.yml
Just tested this on my fork, works.
=> fix(workflows) fix IMAGE_NAME variable

README.md, index.js, public/index.html, public/scripts/network.js, public/scripts/ui.js, public/styles.css, public_included_ws_fallback/index.html, public_included_ws_fallback/scripts/network.js, public_included_ws_fallback/scripts/ui.js, public_included_ws_fallback/styles.css
- Enable renaming as requested in #51 
- Make peerId completely ephemeral
- Stabilize RTCConnection by closing connections cleanly
- Implement Broadcast API
=> Enable renaming of own device

public/index.html, public/scripts/network.js, public/scripts/ui.js, public/styles.css, public_included_ws_fallback/index.html, public_included_ws_fallback/scripts/network.js, public_included_ws_fallback/scripts/ui.js, public_included_ws_fallback/styles.css
=> pairdrop-cli: add fallback if navigator.clipboard.readText() is not available

public/styles.css, public_included_ws_fallback/styles.css
=> Fix display name hidden on Firefox for Android

docs/faq.md, public/scripts/network.js, public/styles.css, public_included_ws_fallback/scripts/network.js, public_included_ws_fallback/styles.css
see #19 
Includes fixes suggested in https://github.com/fm-sys/snapdrop-android/issues/246
=> Compatibility snapdrop android

Dockerfile, docs/docker-swarm-usage.md, docs/host-your-own.md
Hi there,
We would like to add a healthcheck to your amazing fork to further improve your image.
=> Add Healthcheck to Dockerfile

public/scripts/ui.js, public_included_ws_fallback/scripts/ui.js
=> Optimize background animation

public/scripts/ui.js, public/service-worker.js, public_included_ws_fallback/scripts/ui.js, public_included_ws_fallback/service-worker.js
=> WIP: Fix share target API

public/index.html, public/scripts/theme.js, public/styles.css, public_included_ws_fallback/index.html, public_included_ws_fallback/scripts/theme.js, public_included_ws_fallback/styles.css
=> Add theme menu

.github/workflows/github-image.yml
Build image output both for amd64 & arm64 platforms
=> Build multi-architecture image

docs/host-your-own.md, index.js
=> Add debug mode to enable debugging auto discovery

docs/docker-swarm-usage.md, docs/faq.md, docs/host-your-own.md, docs/how-to.md, docs/technical-documentation.md
Was just reading this. Might pile on some other documents from the documentation.(?)
=> Documentation language reworked

public/lang/en.json, public/scripts/ui.js, public_included_ws_fallback/lang/en.json, public_included_ws_fallback/scripts/ui.js
Here is a proposal for a small correction to a lack of translation in a dialog window title.
=> fix dialog transfert request title

public/index.html, public/scripts/ui.js, public/styles.css, public_included_ws_fallback/index.html, public_included_ws_fallback/scripts/ui.js, public_included_ws_fallback/styles.css
=> Fix textarea for sending messages not editable on some iOS devices

public/index.html, public/scripts/localization.js, public/scripts/main.js, public/scripts/ui-main.js, public/scripts/ui.js, server/index.js
Currently deferred scripts are loaded one at a time.
This tries to allow browsers to load them in parallel and still wait for all of them to finish loading.
=> Parallelize and speed up loading of deferred assets, refactor code, and fix `RTC_CONFIG` env var

public/scripts/ui.js, public/styles/styles-deferred.css, public/styles/styles-main.css
=> Release next patch version `1.10.7`

public/scripts/localization.js, public/scripts/network.js, public/scripts/ui.js, public/styles/styles-deferred.css
=> WIP: Add transfer notes: Speed + Time left

.dockerignore, Dockerfile
=> Switch Docker base image to reduce size

README.md
Improved the summary because "List view" was confusing.
=> Improved the summary title in Readme

public/scripts/browser-tabs-connector.js, public/scripts/ui.js, public/styles/styles-main.css
=> Add support for iOS <15.3

public/scripts/network.js, public/scripts/ui.js, public/scripts/util.js, public/styles/styles-main.css
=> Fix share-mode and enable pasting for Firefox users

public/index.html, public/scripts/ui.js, public/scripts/util.js, public/styles/styles-main.css
- Fix padding of auto-accept instruction 
- Fix word-break of base64zip button on mobile
- Fix links in messages cut if ! in path; make regex more readable
=> Fix bugs for 1.11

public/scripts/network.js, public/scripts/ui.js, public/scripts/util.js
=> Fix chromium file extension if mime type is not set 
