- public/index.html
Currently all "action" buttons have a tooltip, while pair/unpair buttons seems to miss it.
This pull just adds the missing `title` attribute on these buttons.
> add: missing pair hover title

- .github/workflows/github-image.yml
Hi. app looks really cool.
This workflow lets you create images for ghcr.io from tagged releases with a semVER version for example: `v0.0.1`.
> feat(ghcr.io)  build container on tagged commits to ghcr.io

- .github/workflows/github-image.yml
| downcase was not valid... so instead its a static name `pairdrop` written instead.
> Fix(ghcr) update workflow variable to a static lowercase name

- .github/workflows/github-image.yml
Fix error:
```log
------
> pushing ghcr.io/pairdrop:v1.1.2 with docker:
------
ERROR: name invalid
Error: buildx call failed with: ERROR: name invalid
```
> Fix(ghcr) update workflow - ERROR: name invalid

- pairdrop-cli/pairdrop
Hi there! I tried to use the CLI on my Mac, but it turns out the script is using the `base64` command incorrectly. Here's [a link](https://www.unix.com/man-page/osx/1/base64/) to the OSX/BSD version, which uses `-b` instead of `-w` and has zero by default, but needs `-i` for the input file. Tested on OSX v13.2.1.
To test:
1. Load these changes on a Mac
2. Try to send a file via the CLI
3. Verify that files are loaded in the website as expected
> Updates CLI to work with OSX base64

- public/scripts/network.js
as you can see [here](https://github.com/RobinLinus/snapdrop/blob/master/client/scripts/network.js#L206) in the snapdrop `_onFileReceived` function the 'file-received'-event needs to send the **file**  -can you try to run this on the test server, maybe this fixes the issue already :)
> fix 'file-received'-event (android app compatibility)

- public/service-worker.js
- public_included_ws_fallback/service-worker.js
This iterates on #72 and fixes passing files from FormData and handling the redirect.
- Fixed FormData key to match the one in Manifest.json: [](https://github.com/schlagmichdoch/PairDrop/blob/5b39709e4a54d7fd6a1b70703ccc3b991bd93eef/public/manifest.json#L78)
- Fetch POST redirect should now work (found a way to get it working from a google post, don't know why it didn't work before this 🤷)
Also, working demo here: https://pwafixtest.onrender.com/
> Fixed sharing to the PWA on phones

- public/styles.css
- public_included_ws_fallback/styles.css
It is now based on vw/vh instead of px. It can also easily be adjusted, mostly. There is no way it will not fill up the viewport. The Animation may not be the same speed anymore, but it will be consistent across devices and viewport sizes.
> Fix About Background not filling up full viewport under certain circumstances

- docs/host-your-own.md
- index.js
> Add new env var `IPV6_LOCALIZE` to enable auto discovery for IPv6 addresses

- public/scripts/network.js
We're planning to add vibration effects in the android app. This event would be helpful for us. See https://github.com/fm-sys/snapdrop-android/pull/299
Alternatives:
Use the HTML5 vibration API to archive this behavior natively in Pairdrop. However, vibration API is only supported by chrome, not Firefox or Safari.
> Add 'files-sent' event

- pairdrop-cli/pairdrop
1. By default, Windows bash does not include the 'zip' command. Therefore, I replaced it with the 'Compress-Archive' command in powershell.exe.
2. When I tested the command for transfering folder, I found a bug like the image as below. Thus I revise the zipTempPath from the original path to the updated bug-free path.
> revise the command line tool

- docs/host-your-own.md
Added note about using an alternate TURN server like OpenRelay.
> Add alternate TURN server option to config notes

- public/index.html
- public/scripts/localization.js
- public/scripts/main.js
- public/scripts/ui-main.js
- public/scripts/ui.js
- server/index.js
Currently deferred scripts are loaded one at a time.
This tries to allow browsers to load them in parallel and still wait for all of them to finish loading.
> Parallelize and speed up loading of deferred assets, refactor code, and fix `RTC_CONFIG` env var

- public/scripts/ui.js
- public/scripts/util.js
Fix Error Invalid Group Specifier Name on Safari by removing REGEX lookbehind group construct (fixes #239 and fixes #246)
> Fix Error Invalid Group Specifier Name on Safari

- public/scripts/ui.js
- public/styles/styles-deferred.css
>  WIP: Release Next Minor Version `v1.11.0`

- README.md
In the "Differences to the Snapdrop" > "Paired Devices Public Rooms" section, the following feature was repeated twice:
"Connect to devices on your mobile hotspot" (in bullet 3 and 4)
This pull request aims to fix it.
> Removed duplicate feature in README.md

- public/scripts/browser-tabs-connector.js
- public/scripts/network.js
- public/scripts/ui-main.js
- public/scripts/ui.js
- server/ws-server.js
> Leave old public room when switching public rooms

- public/index.html
On iOS, when the app runs as a PWA without this line, there will be a blue bar at the top of the screen. Implementing this setting will make for a more seamless UI on iOS, as documented below.
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html
Before `apple-mobile-web-app-status-bar-style`:
After `apple-mobile-web-app-status-bar-style`:
> Remove bar at top of screen on iOS

- public/index.html
- public/manifest.json
- public/scripts/main.js
- public/scripts/ui-main.js
- public/styles/styles-main.css
> Enable standalone mode for PWA

- public/manifest.json
It looks like with the last update, the PWA install button in Chrome-based browsers no longer appears. Adding the `start_url`  line resolves this and restores that functionality. This change also retains the PWA functionality we expect on mobile devices, as tested on my iPhone.
> Restore desktop Chrome PWA button
